// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjN5BaMjTtOLE8tI0zWxD1crAxZxNUNNc',
    appId: '1:922141209659:web:3200b86dcb62c76cb1581e',
    messagingSenderId: '922141209659',
    projectId: 'math-solver-c9c9a',
    authDomain: 'math-solver-c9c9a.firebaseapp.com',
    storageBucket: 'math-solver-c9c9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaFRAGSCQwo9op9jucTTYZPY3xA05zk0c',
    appId: '1:922141209659:android:29f9d15a2c310e35b1581e',
    messagingSenderId: '922141209659',
    projectId: 'math-solver-c9c9a',
    storageBucket: 'math-solver-c9c9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKqvHD3c5viwUcKQFmP1XmDHQtqbuQ62k',
    appId: '1:922141209659:ios:effac1ce7ef4a321b1581e',
    messagingSenderId: '922141209659',
    projectId: 'math-solver-c9c9a',
    storageBucket: 'math-solver-c9c9a.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKqvHD3c5viwUcKQFmP1XmDHQtqbuQ62k',
    appId: '1:922141209659:ios:effac1ce7ef4a321b1581e',
    messagingSenderId: '922141209659',
    projectId: 'math-solver-c9c9a',
    storageBucket: 'math-solver-c9c9a.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjN5BaMjTtOLE8tI0zWxD1crAxZxNUNNc',
    appId: '1:922141209659:web:5b7deadda61a7ca8b1581e',
    messagingSenderId: '922141209659',
    projectId: 'math-solver-c9c9a',
    authDomain: 'math-solver-c9c9a.firebaseapp.com',
    storageBucket: 'math-solver-c9c9a.firebasestorage.app',
  );
}
