name: math-teacher-frontend

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: math-teacher-web
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
