name: math-teacher

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: math-teacher-api
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: math-teacher-web
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://math-teacher-api:8000
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
